### ISSUE TITLE
nette 2.4

### ISSUE THREAD

**Issue by JStika** [contributte/forms-wizard#15]
I'm geting error:

Class 'Contributte\FormWizard\DI\WizardExtension' not found

when I did to add to extension.neon

extensions:
    - Contributte\FormWizard\DI\WizardExtension

What is the solution.
Can you help me, please?

**Comment by JStika** [comment]
I forgot info, I got "contributte/forms-wizard": "^2.1@dev" after install

**Comment by f3l1x** [comment]
Hey man. Namespace has changed since v3.0. 

Take a look at 2.0 readme https://github.com/contributte/forms-wizard/blob/2.0.1/README.md

**Comment by JStika** [comment]
Very, very big thank you for fast answer.

**Comment by JStika** [comment]
I have a request. 
Can you show me an example of how to use radioboxes in the table (after selecting the radiobox, the next button would be enabled, otherwise it would be disabled) in the first step.

Thank you.

**Comment by JStika** [comment]
How can I set up in construct from presenter $lang and $userId?

**Comment by MartkCz** [comment]
1. Imho

```php
protected function createStep2(): Form 
{
    $values = $this->getValues();
    if ($values['inputName']) {
        $input->setDisabled();
    }
}
```

2. via factory

```php
interface MyWizardFactory {

    public function create(string $lang, int $userId): MyWizard;

}

class MyWizard extends Wizard {

    __constructor(Session $session, string $lang, int $userId)

}
```

**Comment by f3l1x** [comment]
Feel free to ask about anything. Closing issue here.
