### ISSUE TITLE
Wizard is not intended to be used in the Presenter

### ISSUE THREAD

**Issue by martinjinda** [contributte/forms-wizard#25]
I wanted to try it so I just copy&paste the tutorial from Docs (I just use it with my own component) and I am getting Notice that is not intended to be used in Presenter with debug mode on. I don't understand this notice where else I should use it? Do you guys have another approach to how I should use it?

![Screenshot 2021-03-18 at 10 58 25](https://user-images.githubusercontent.com/9948632/111607796-dfa8cf00-87d8-11eb-8cf1-cb66b2054739.png)

Using:
- contributte/forms-wizard 3.0
- php: 7.4
- Nette 3.0

**Comment by vanam** [comment]
Caused by https://github.com/nette/forms/issues/147

**Comment by martinjinda** [comment]
Fixed with #27.

**Comment by f3l1x** [comment]
Thanks @martinjinda for letting us know.

**Comment by f3l1x** [comment]
#27 merged
